quarkus.management.enabled=true
quarkus.management.port=9000
quarkus.micrometer.export.prometheus.path=metrics
quarkus.micrometer.binder.http-server.match-patterns=/ok=/ok,/missing=/missing,/client-error=/client-error,/server-error=/server-error
