micronaut.application.name=micronaut-metrics-demo
micronaut.server.host=127.0.0.1
micronaut.server.port=18084
micronaut.metrics.enabled=true
endpoints.prometheus.sensitive=false
endpoints.health.sensitive=false
